<?php
/**
 * WooCommerce Yoast SEO plugin file.
 *
 * @package WPSEO/WooCommerce
 */

/**
 * Class WPSEO_WooCommerce_Breadcrumbs
 */
class WPSEO_WooCommerce_Breadcrumbs {

	/**
	 * Registers the hooks.
	 */
	public function register_hooks() {
		add_filter( 'woocommerce_get_breadcrumb', [ $this, 'filter_breadcrumbs_array' ], 99 );
	}

	/**
	 * Filters the WooCommerce breadcrumbs array, replaces the array of links with links generated by Yoast SEO.
	 *
	 * @param array $crumbs The crumbs.
	 *
	 * @return array The crumbs.
	 */
	public function filter_breadcrumbs_array( $crumbs ) {
		$new_crumbs = YoastSEO()->meta->for_current_page()->breadcrumbs;
		foreach( $new_crumbs as $key => $crumb ) {
			$new_crumbs[ $key ][0] = $crumb['text'];
			$new_crumbs[ $key ][1] = $crumb['url'];
		}
		return $new_crumbs;
	}
}
